import { useState } from 'react';
import { adminReportsList } from '../../data/mockData';
import './Reports.css';

const reportTypes = [
  { id: 'census', label: 'Daily Census', description: 'Patient count by ward and status' },
  { id: 'ot', label: 'OT Utilization', description: 'Operating theatre usage and conflicts' },
  { id: 'admissions', label: 'Admissions', description: 'Weekly admission and discharge summary' },
  { id: 'clinical', label: 'Clinical Summary', description: 'Key clinical metrics and outcomes' },
  { id: 'alerts', label: 'Alerts & Escalations', description: 'System and clinical alerts report' },
];

export default function Reports() {
  const [selectedType, setSelectedType] = useState('');
  const [dateRange, setDateRange] = useState({ from: '', to: '' });
  const [generating, setGenerating] = useState(false);

  const handleGenerate = () => {
    if (!selectedType) return;
    setGenerating(true);
    setTimeout(() => setGenerating(false), 1500);
  };

  return (
    <div className="reports-page page-enter">
      <div className="reports-page__header">
        <h1 className="reports-page__title">Reports</h1>
        <p className="reports-page__desc">Clinical and operational reports. Generate new reports or view recent ones.</p>
      </div>

      <div className="reports-page__grid">
        <div className="reports-page__card reports-page__generate-card">
          <h2 className="reports-page__card-title">Generate Report</h2>
          <div className="reports-page__form">
            <label className="reports-page__label">
              Report type
              <select
                className="reports-page__select"
                value={selectedType}
                onChange={(e) => setSelectedType(e.target.value)}
              >
                <option value="">Select...</option>
                {reportTypes.map((t) => (
                  <option key={t.id} value={t.id}>{t.label}</option>
                ))}
              </select>
            </label>
            <label className="reports-page__label">
              From date
              <input
                type="date"
                className="reports-page__input"
                value={dateRange.from}
                onChange={(e) => setDateRange((r) => ({ ...r, from: e.target.value }))}
              />
            </label>
            <label className="reports-page__label">
              To date
              <input
                type="date"
                className="reports-page__input"
                value={dateRange.to}
                onChange={(e) => setDateRange((r) => ({ ...r, to: e.target.value }))}
              />
            </label>
            <button
              type="button"
              className="reports-page__btn"
              onClick={handleGenerate}
              disabled={!selectedType || generating}
            >
              {generating ? 'Generating…' : 'Generate Report'}
            </button>
          </div>
        </div>

        <div className="reports-page__card">
          <h2 className="reports-page__card-title">Report types</h2>
          <ul className="reports-page__types">
            {reportTypes.map((t) => (
              <li key={t.id}>
                <span className="reports-page__type-name">{t.label}</span>
                <span className="reports-page__type-desc">{t.description}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="reports-page__card reports-page__recent">
        <h2 className="reports-page__card-title">Recent reports</h2>
        <table className="reports-page__table">
          <thead>
            <tr>
              <th>Report name</th>
              <th>Type</th>
              <th>Date</th>
              <th>Generated by</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {adminReportsList.map((r) => (
              <tr key={r.id}>
                <td className="reports-page__name">{r.name}</td>
                <td>{r.type}</td>
                <td>{r.date}</td>
                <td>{r.generatedBy}</td>
                <td>
                  <button type="button" className="reports-page__action">Download</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
