-- CDSS Clinical Database Schema (PostgreSQL)
-- Focus: Patient records, surgery planning, and clinical consultations

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Doctors Table
CREATE TABLE doctors (
    doctor_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name VARCHAR(100) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Patients Table (DISHA Compliant structure)
CREATE TABLE patients (
    patient_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    abdm_id VARCHAR(50) UNIQUE, -- Ayushman Bharat Digital Mission ID
    full_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    phone_number VARCHAR(20),
    blood_group VARCHAR(5),
    ward_number VARCHAR(20),
    bed_number VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Vitals History
CREATE TABLE vitals_history (
    id SERIAL PRIMARY KEY,
    patient_id UUID REFERENCES patients(patient_id),
    hr INT,
    bp_systolic INT,
    bp_diastolic INT,
    spo2 INT,
    temp_f NUMERIC(5,2),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Consultations
CREATE TABLE consultations (
    consultation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES patients(patient_id),
    doctor_id UUID REFERENCES doctors(doctor_id),
    notes TEXT,
    ai_summary TEXT, -- Summary generated by PatientAgent
    consultation_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Clinical Conditions
CREATE TABLE conditions (
    condition_id SERIAL PRIMARY KEY,
    patient_id UUID REFERENCES patients(patient_id),
    condition_name VARCHAR(200) NOT NULL,
    onsett_date DATE,
    status VARCHAR(50) DEFAULT 'active'
);

-- Prescriptions
CREATE TABLE prescriptions (
    prescription_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES patients(patient_id),
    doctor_id UUID REFERENCES doctors(doctor_id),
    medication_name VARCHAR(200) NOT NULL,
    dosage VARCHAR(100),
    frequency VARCHAR(100),
    start_date DATE,
    end_date DATE,
    instructions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Surgery Plans
CREATE TABLE surgery_plans (
    surgery_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES patients(patient_id),
    lead_surgeon_id UUID REFERENCES doctors(doctor_id),
    surgery_type VARCHAR(200) NOT NULL,
    ot_room_id VARCHAR(50),
    planned_start_time TIMESTAMP WITH TIME ZONE,
    planned_duration_min INT,
    status VARCHAR(50) DEFAULT 'scheduled', -- scheduled, in-prep, pre-op, active, completed, cancelled
    pre_op_checklist JSONB, -- Generated by SurgeryPlanningAgent
    instruments_required JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Appointments
CREATE TABLE appointments (
    appointment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES patients(patient_id),
    doctor_id UUID REFERENCES doctors(doctor_id),
    appointment_time TIMESTAMP WITH TIME ZONE NOT NULL,
    type VARCHAR(50), -- Consultation, Procedure, Follow-up
    status VARCHAR(50) DEFAULT 'booked',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed Data (Initial Admin Doctor)
INSERT INTO doctors (full_name, specialization, department, email)
VALUES ('Dr. Priya Sharma', 'General Medicine', 'Internal Medicine', 'priya.sharma@hospital.com');
